name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dotnet build
      run: dotnet build --configuration Release

    - name: Dotnet test
      run: dotnet test

    - name: Typescript install
      run: npm ci
      working-directory: ./DotnetTemplate.Web

    - name: Typescript build
      run: npm run build
      working-directory: ./DotnetTemplate.Web

    - name: Typescript test
      run: npm run test
      working-directory: ./DotnetTemplate.Web

#  build:
#    name: Build and Deploy
#    runs-on: ubuntu-latest
#    needs: [Build and test]
#    steps:
    - name: Build Image
      run: docker build --tag m8 .

    - name: Change Tag
      run: docker tag m8 wishy78/dotnettemplate:m8

    - name: Login to Docker hub
      run: docker login --username wishy78 --password "${{ secrets.DOCKER_PASSWORD }}"

    - name: Publish to Docker hub
      run: docker push wishy78/dotnettemplate:m8
